### ISSUE TITLE
Documentar lista de handlres

### ISSUE THREAD

**Issue by davicav** [fabiocerqueira/easydojo#1]
Adicionar na documentação a lista de handlers suportados

**Comment by fabiocerqueira** [comment]
O comando `easy_dojo list` faz isso, mas era legal ter no README também

**Comment by davicav** [comment]
Vi que o list faz isso. Mas seria interessante ter no próprio help. Retirava o comando list e deixava apenas no help. A não ser que terá inúmeros handlers. O que tu acha?

**Comment by fabiocerqueira** [comment]
Acho que pode manter os dois, visto que o comando list já pega o handler e a documentação de forma automática.
